version: '3'

tasks:
  zip-datasets:
    cmds:
      - zip -r datasets.zip datasets/ -x "*/raw/*"

  upload-datasets:
    cmds:
      - task: zip-datasets
      - gsutil cp datasets.zip gs://xiaoqiwang-public/datasets.zip

  clean:
    cmds:
      - rm datasets.zip